# Generated by Django 4.2.4 on 2023-08-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='url',
        ),
        migrations.AlterField(
            model_name='actor',
            name='description',
            field=models.TextField(max_length=2255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
    ]
