# Generated by Django 4.2.4 on 2023-08-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_actor_url_alter_actor_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=2255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(default='2000', verbose_name='Дата выхода'),
        ),
    ]
